### PR TITLE
Fixed a crash which would occur when performing a 'look' in a room co…

### PR DESCRIPTION
**Pull request by JordanWhittle**
Hi I've never made a pull request before so I'm trying that out.

I have fixed a crash which would occur when performing a 'look' in a room containing an unnamed player.

### CODE REVIEW

**Comment by 0smo5is** [comment]
Seems good! I'm new, working on a fork of mud-pi. Is there a way to pull this into my master branch? Or do i have to add it manually?

**Comment by Frimkron** [comment]
Good find, Jordan - thank you 😄 
I've also made a change so that new players start with their room as None, so that they don't receive chat from the starting room like some kind of ghostly eavesdropper 😜

**Comment by Frimkron** [comment]
@0smo5is If you add my version (the upstream) as a remote...

`git remote add upstream https://github.com/Frimkron/mud-pi`

...then you can track the latest changes by fetching from this remote....

`git fetch upstream`

...and merging into your own branch

`git merge upstream/master`

More info here: https://help.github.com/articles/syncing-a-fork/

Or if you want to benefit _immediately_ from Jordan's changes, you can add their fork as a remote and fetch changes from there too :smile:

**Comment by 0smo5is** [comment]
@Frimkron Thanks for the help!

**Pull request merged**
